language: node_js

node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - /home/travis/.elm/0.19.0/package

os:
  - osx
  - linux

before_install:
  - node --version
  - npm --version
  - npm install -g elm

install:
  - npm install

script:
  - npm run build
  - npm run test-lint
  - npm run test-unit-coveralls
  - npm run test-integration
