environment:
  ELM_VERSION: "0.18.0"
  matrix:
  - nodejs_version: "4.6"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install

test_script:
  - npm test-ci

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem ./test-result -Name -Recurse '-tests.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }

build: off
