environment:
  ELM_VERSION: "0.17.1"
  matrix:
  - nodejs_version: "4.6"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm test

build: off
